ALTER TABLE `scores`  ADD `Quarry` INT(5) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `scores`  ADD `Magic` INT(5) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `scores`  ADD `Dungeons` INT(5) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `scores`  ADD `Rares` INT(5) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `scores`  ADD `Tower` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `scores`  ADD `Wall` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `scores`  ADD `TowerDamage` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `scores`  ADD `WallDamage` INT(10) UNSIGNED NOT NULL DEFAULT '0';
