SET AUTOCOMMIT=0;

START TRANSACTION;

ALTER TABLE `decks` DROP PRIMARY KEY;

ALTER TABLE `decks`  ADD `DeckID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,  ADD PRIMARY KEY (DeckID);

ALTER TABLE `decks` ADD INDEX(`Username`);

COMMIT;
