ALTER TABLE `decks`  ADD `Wins` INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER `Data`;
ALTER TABLE `decks`  ADD `Losses` INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER `Wins`;
ALTER TABLE `decks`  ADD `Draws` INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER `Losses`;
