SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

RENAME TABLE `decks` TO `deck`;

ALTER TABLE `deck` CHANGE `DeckID` `deck_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
CHANGE `Username` `username` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
CHANGE `Deckname` `deck_name` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
CHANGE `Ready` `is_ready` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Data` `data` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
CHANGE `Note` `note` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
CHANGE `Wins` `wins` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Losses` `losses` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Draws` `draws` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Shared` `is_shared` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Modified` `modified_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
