SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

RENAME TABLE `settings` TO `setting`;

ALTER TABLE `setting` CHANGE `Username` `username` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
CHANGE `Firstname` `first_name` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
CHANGE `Surname` `surname` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
CHANGE `Birthdate` `birth_date` DATE NOT NULL DEFAULT '1000-01-01',
CHANGE `Gender` `gender` ENUM('none','male','female') CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'none',
CHANGE `Email` `email` VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
CHANGE `Imnumber` `im_number` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
CHANGE `Country` `country` VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'Unknown',
CHANGE `Hobby` `hobby` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
CHANGE `Avatar` `avatar` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'noavatar.jpg',
CHANGE `Status` `status` ENUM('newbie','ready','quick','dnd','none') CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'newbie',
CHANGE `FriendlyFlag` `friendly_flag` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `BlindFlag` `blind_flag` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `LongFlag` `long_flag` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Timezone` `timezone` CHAR(3) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
CHANGE `Insignias` `keyword_insignia` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
CHANGE `PlayButtons` `play_card_button` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
CHANGE `Chatorder` `chat_reverse_order` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `IntegratedChat` `integrated_chat` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Avatargame` `in_game_avatar` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
CHANGE `OldCardLook` `old_card_look` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Miniflags` `card_mini_flag` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Reports` `battle_report` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Forum_notification` `forum_notification` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
CHANGE `Concepts_notification` `concept_notification` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
CHANGE `Skin` `skin` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Background` `game_bg_image` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `DefaultFilter` `default_player_filter` ENUM('none','active','offline','all') CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'none',
CHANGE `Autorefresh` `auto_refresh_timer` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `AutoAi` `auto_ai_timer` TINYINT(2) UNSIGNED NOT NULL DEFAULT '5',
CHANGE `RandomDeck` `use_random_deck` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
CHANGE `GameLimit` `unique_game_opponent` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Timeout` `game_turn_timeout` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `FoilCards` `foil_cards` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
