SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

RENAME TABLE `scores` TO `score`;

ALTER TABLE `score` CHANGE `Username` `username` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
CHANGE `Level` `level` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Exp` `exp` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Gold` `gold` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Wins` `wins` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Losses` `losses` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Draws` `draws` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `GameSlots` `game_slots` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Assassin` `assassin` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Builder` `builder` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Carpenter` `carpenter` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Collector` `collector` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Desolator` `desolator` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Dragon` `dragon` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Gentle_touch` `gentle_touch` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Saboteur` `saboteur` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Snob` `snob` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Survivor` `survivor` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Titan` `titan` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Quarry` `quarry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Magic` `magic` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Dungeons` `dungeons` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Rares` `rares` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Tower` `tower` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Wall` `wall` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `TowerDamage` `tower_damage` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `WallDamage` `wall_damage` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
CHANGE `Challenges` `ai_challenges` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0';
