ALTER TABLE `games`  ADD `Current` CHAR(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL AFTER `State`,  ADD `Round` INT(3) UNSIGNED NOT NULL DEFAULT '1' AFTER `Current`,  ADD `Winner` CHAR(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '' AFTER `Round`,  ADD `Outcome` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '' AFTER `Winner`,  ADD `Last Action` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `Outcome`;

ALTER TABLE `games` CHANGE `State` `State` CHAR(16) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'waiting';
ALTER TABLE `games` CHANGE `GameID` `GameID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;
